---
title: "Examples"
format:
  html:
    code-fold: true
    code-tools: true
    toc: false
---

```{r include=FALSE}
library(heattree)
knitr::opts_chunk$set(
  message = FALSE,
  collapse = TRUE,
  comment = "#>"
  )
```

## Phytools datasets

The [`phytools`](https://github.com/liamrevell/phytools) package has many example trees with associated metadata, ideal for use with `heattree`.
Below is all of these data sets in a single `heattree` widget.

```{r}
# Load required datasets from phytools
library(phytools)
data(anole.data)
data(anoletree)
data(bonyfish.data)
data(bonyfish.tree)
data(butterfly.data)
data(butterfly.tree)
data(eel.data)
data(eel.tree)
data(flatworm.data)
data(flatworm.tree)
data(mammal.data)
data(mammal.tree)
data(primate.data)
data(primate.tree)
data(sunfish.data)
data(sunfish.tree)
data(tropidurid.data)
data(tropidurid.tree)

# Create tree widget
library(heattree)
heat_tree(
  tree = list(
    'Anoles' = anoletree,
    'Bony fishs' = bonyfish.tree,
    'Butterflies' = butterfly.tree,
    'Eels' = eel.tree,
    'Flatworms' = flatworm.tree,
    'Mammals' = mammal.tree,
    'Primates' = primate.tree,
    'Sunfishes' = sunfish.tree,
    'Tortoises' = tropidurid.tree
  ),
  metadata = list(
    anole.data,
    bonyfish.data,
    butterfly.data,
    eel.data,
    flatworm.data,
    mammal.data,
    primate.data,
    sunfish.data,
    tropidurid.data
  ),
  aesthetics = list(
    c(tipLabelColor = 'SVL'),
    c(tipLabelColor = 'paternal_care'),
    c(tipLabelColor = 'habitat'),
    c(tipLabelColor = 'feed_mode'),
    c(tipLabelColor = 'Habitat'),
    c(tipLabelColor = 'bodyMass'),
    c(tipLabelColor = 'Skull_length'),
    c(tipLabelColor = 'buccal.length'),
    c(tipLabelColor = 'body_height')
  ),
  layout = 'circular'
)
```



## Weisberg et al. 2020

```{r}
library(readxl)
library(ape)
library(heattree)

# Read and format metadata for use with trees
metadata <- read.table('inst/extdata/weisberg_2020_s1.tsv', sep = '\t', header = TRUE)
metadata$Strain.ID[is.na(metadata$Strain.ID)] <- ''
metadata$`3-letter code*`[is.na(metadata$`3-letter code*`)] <- ''
metadata$mlsa_node_id <- paste0(metadata$Strain.ID, '__', metadata$`3-letter code*`)
metadata$mlsa_node_id <- gsub(metadata$mlsa_node_id, pattern = '[/ ]', replacement = '_')
metadata$beast_node_id <- gsub(metadata$Strain.ID, pattern = '[/ ]', replacement = '_')

# Load MLSA tree and subset for available metadata
tree_mlsa <- read.tree('inst/extdata/wiesberg_2020_mlsa.tre')
shared_ids <- tree_mlsa$tip.label[tree_mlsa$tip.label %in% metadata$mlsa_node_id]
tree_mlsa_subset <- keep.tip(tree_mlsa, shared_ids)

# Load BEAST tree and subset for available metadata
tree_beast <- read.nexus('inst/extdata/wiesberg_2020_beast.tre')
shared_ids <- tree_beast$tip.label[tree_beast$tip.label %in% metadata$beast_node_id]
tree_beast_subset <- keep.tip(tree_beast, shared_ids)

# Plot both trees in the same widget
heat_tree(
  tree = list('MLSA' = tree_mlsa_subset, 'BEAST' = tree_beast_subset),
  metadata = list(metadata, metadata),
  aesthetics = list(c(tipLabelText = 'Strain.ID'), c(tipLabelText = 'Strain.ID')),
  layout = 'circular'
)
```

